apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: test1
  name: test1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1
  namespace: test1
  labels:
    app: busybox1
  annotations:
    testAnnotation: randomVal
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox1
  template:
    metadata:
      labels:
        app: busybox1
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: test2
  name: test2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox2
  namespace: test2
  labels:
    app: busybox2
  annotations:
    testAnnotation: randomVal
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox2
  template:
    metadata:
      labels:
        app: busybox2
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']