# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#   name: chaos
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   url: https://github.com/raghurps/chaos
#   ref:
#     branch: main
#   ignore: |
#     # exclude all
#     /*
#     # include charts directory
#     !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaosmonkey
  namespace: flux-system
spec:
  targetNamespace: chaosmonkey
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/chaos
      sourceRef:
        kind: GitRepository
        name: chaos
      valuesFile: hack/values.yaml
